### ISSUE TITLE
Updating the search to full page does not work

### ISSUE THREAD

**Issue by kristiannordestgaard** [thesowah/wangana#13]
Great theme, thanks a bunch. When I try to update the [Simple-Jekyll-Search](https://github.com/christian-fei/Simple-Jekyll-Search) to full page, as per [this](https://github.com/christian-fei/Simple-Jekyll-Search#enabling-full-text-search), it stops working completely. I tried replacing all the relevant code, but no luck. Can you you help?

**Comment by nadjetey** [comment]
But when you revert your changes, does it still function?

**Comment by nadjetey** [comment]
Let me know if this works for you, 
```json
---
---
[
  {% for post in site.posts %}
    {
      "title"    : "{{ post.title | escape }}",
      "category" : "{{ post.category }}",
      "tags"     : "{{ post.tags | join: ', ' }}",
      "url"      : "{{ site.baseurl }}{{ post.url }}",
      "date"     : "{{ post.date }}"
    } {% unless forloop.last %},{% endunless %}
  {% endfor %}
  ,
  {% for page in site.pages %}
   {
     {% if page.title != nil %}
        "title"    : "{{ page.title | escape }}",
        "category" : "{{ page.category }}",
        "tags"     : "{{ page.tags | join: ', ' }}",
        "url"      : "{{ site.baseurl }}{{ page.url }}",
        "date"     : "{{ page.date }}"
     {% endif %}
   } {% unless forloop.last %},{% endunless %}
  {% endfor %}
]
```

If this works, then I can tell what you did wrong

**Comment by kristiannordestgaard** [comment]
Thanks for getting back to me. This does not work, though.

**Comment by kristiannordestgaard** [comment]
... I tried again with a freshly cloned theme, still no luck.

**Comment by nadjetey** [comment]
I'm not sure why its behaving like that. When you find out, kindly let me know

**Comment by kristiannordestgaard** [comment]
I have no idea why it won't work, if I did I would let you know of course.
