### ISSUE TITLE
how to use math latex in your template?

### ISSUE THREAD

**Issue by kirk86** [thesowah/wangana#15]
Hi I've tried your template because its nice and lean. I would like to be able to use latex math in side my posts and pages do you have any idea how I can do that?

I've noticed that if you type an equation its being parsed partially. What I mean is the following.
if you have something like `y = ax^2+\hat{b}` then the `\hat{b}` part is not being rendered correctly.
The part that is being rendered correctly from the above equation is translated in to html and not in to javascript like mathjax would do.

I've tried adding mathjax into the header.html and then to footer.html but none of those options worked. I also tried to change redcarpet to kmarkdown but still no success.

I am using org-mode to produce the html pages in case that helps.

Thanks in advance!

**Comment by nadjetey** [comment]
The math latex part was contributed by someone else, when you figure it out, kindly make a pull request so that I update this repo. I wish I could be of more help.

**Comment by kirk86** [comment]
It seems that one has to enable `mathjax`!
